### ISSUE TITLE
bitcoin.conf mixin

### ISSUE THREAD

**Issue by unwriter** [zquestz/docker-bitcoin#2]
Currently the `bitcoin.conf` file is [hardcoded](https://github.com/zquestz/docker-bitcoin/blob/master/abc/0.18.0/docker-entrypoint.sh#L7).

In my case I have a lot of customization in bitcoin.conf such as:

- zeromq broadcast address
- rpcworkqueue
- rpcallowip
- dbcache
- more

To allow more flexibility I think it would be great to have a customization option, and actually think this may be THE part where using volumes might be necessary. For example, under the [volumes:](https://github.com/zquestz/docker-bitcoin/blob/master/example/docker-compose.yml#L12) item in docker-compose, I can imagine something like:

```
volumes:
  - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
```

But this is just my quick idea from top of my head, maybe there are better solutions?

**Comment by zquestz** [comment]
This is already handled by the volume. You can place any bitcoin.conf you want into the data directory and it will happily use it.

If you look at the startup script, it only copies the bitcoin.conf over if it doesn't already exist on the volume.

```
	if [[ ! -s "$BITCOIN_DATA/bitcoin.conf" ]]; then
		cat <<-EOF > "$BITCOIN_DATA/bitcoin.conf"
		printtoconsole=1
		rpcallowip=::/0
		rpcpassword=${BITCOIN_RPC_PASSWORD:-password}
		rpcuser=${BITCOIN_RPC_USER:-bitcoin}
		EOF
		chown bitcoin:bitcoin "$BITCOIN_DATA/bitcoin.conf"
	fi
```

**Comment by unwriter** [comment]
I don't know how I completely missed it, I even linked to that exact "if condition" line as an "evidence". Sorry about that! Closing.
