### ISSUE TITLE
Issue adding -rest or -testnet to bitcoin.conf

### ISSUE THREAD

**Issue by daynaskully** [zquestz/docker-bitcoin#8]
I was unable to determine the proper syntax for adding either arguments via bitcoin.conf.

It has mentioned here to "see below" https://github.com/zquestz/docker-bitcoin#configuring-bitcoin but there was no additional explanation on how to get -testnet read from the config file.

I looked into the advanced examples folder on this repo and didn't find anything there either.

I'm particularly interested in running the rest api (bitcoind -rest) and would love to know how to add this via the bitcoin.conf file - or alternatively if an ENV variable could be used.

**Comment by zquestz** [comment]
On the data volume you just need to make sure your conf is there. When it gets mounted it will automatically be symlinked to the ~/.bitcoin directory for you.  You can put whatever you want in the configuration. Most users don't bother with this and just pass in additional flags when starting bitcoind. That also works.
